package me.melchscat.aura.myNPC;

public enum AuraStartNpcAnimationStatus {
    AURA_START_NPC_IDLE_POT(),
    AURA_START_NPC_SHAKE_POT(),
    AURA_START_NPC_TALK_POT(),
    AURA_START_NPC_SULK_POT(),
    AURA_START_NPC_ACCEPT_POT(),
    AURA_START_NPC_CALL_POT(),
    AURA_START_NPC_RELEASE1_POT(),
    AURA_START_NPC_RELEASE2_POT(),
    AURA_START_NPC_RELEASE3_POT(),
    AURA_START_NPC_RELEASE4_POT();
}
